/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pfc_lib_DllEntry */

#ifndef _Included_com_pfc_lib_DllEntry
#define _Included_com_pfc_lib_DllEntry
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pfc_lib_DllEntry
 * Method:    cod128
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pfc_lib_DllEntry_cod128
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_pfc_lib_DllEntry
 * Method:    dec128
 * Signature: (Ljava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_com_pfc_lib_DllEntry_dec128
  (JNIEnv *, jclass, jstring, jbyteArray);

/*
 * Class:     com_pfc_lib_DllEntry
 * Method:    dec64
 * Signature: (Ljava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_com_pfc_lib_DllEntry_dec64
  (JNIEnv *, jclass, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
