/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pfc_lib_UsbSmb */

#ifndef _Included_com_pfc_lib_UsbSmb
#define _Included_com_pfc_lib_UsbSmb
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pfc_lib_UsbSmb
 * Method:    usbInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_pfc_lib_UsbSmb_usbInit
  (JNIEnv *, jobject);

/*
 * Class:     com_pfc_lib_UsbSmb
 * Method:    usbGetVersion
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_com_pfc_lib_UsbSmb_usbGetVersion
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_pfc_lib_UsbSmb
 * Method:    usbSmbWrite
 * Signature: (IBBZI[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pfc_lib_UsbSmb_usbSmbWrite
  (JNIEnv *, jobject, jint, jbyte, jbyte, jboolean, jint, jbyteArray);

/*
 * Class:     com_pfc_lib_UsbSmb
 * Method:    usbSmbRead
 * Signature: (IBBZI[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pfc_lib_UsbSmb_usbSmbRead
  (JNIEnv *, jobject, jint, jbyte, jbyte, jboolean, jint, jbyteArray);

/*
 * Class:     com_pfc_lib_UsbSmb
 * Method:    usbHdqWrite
 * Signature: (IBB)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pfc_lib_UsbSmb_usbHdqWrite
  (JNIEnv *, jobject, jint, jbyte, jbyte);

/*
 * Class:     com_pfc_lib_UsbSmb
 * Method:    usbHdqRead
 * Signature: (IB[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pfc_lib_UsbSmb_usbHdqRead
  (JNIEnv *, jobject, jint, jbyte, jbyteArray);

/*
 * Class:     com_pfc_lib_UsbSmb
 * Method:    usbEepromWrite
 * Signature: (II[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pfc_lib_UsbSmb_usbEepromWrite
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     com_pfc_lib_UsbSmb
 * Method:    usbEepromRead
 * Signature: (II[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pfc_lib_UsbSmb_usbEepromRead
  (JNIEnv *, jobject, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
