/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pfc_lib_ReadWriteDF */

#ifndef _Included_com_pfc_lib_ReadWriteDF
#define _Included_com_pfc_lib_ReadWriteDF
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pfc_lib_ReadWriteDF
 * Method:    readDataFlash
 * Signature: (II[BZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pfc_lib_ReadWriteDF_readDataFlash
  (JNIEnv *, jclass, jint, jint, jbyteArray, jboolean);

/*
 * Class:     com_pfc_lib_ReadWriteDF
 * Method:    writeDataFlash
 * Signature: (II[BZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pfc_lib_ReadWriteDF_writeDataFlash
  (JNIEnv *, jclass, jint, jint, jbyteArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
